#!/usr/bin/env python3
from __future__ import annotations

import json
import struct
from pathlib import Path
from typing import Any

SCRIPT_DIR = Path(__file__).resolve().parent
APP_DIR = SCRIPT_DIR.parent
REFERENCE_DIR = APP_DIR / "reference" / "littlest-tokyo"
ORIGINAL_GLB = REFERENCE_DIR / "models" / "gltf" / "LittlestTokyo.glb"

GENERATED_TS_PATH = APP_DIR / "src" / "generatedLittlestTokyoReference.ts"
GENERATED_SCENE_SOURCE_PATH = APP_DIR / "src" / "referenceLittlestTokyoSceneSource.ts"
OFFICIAL_HTML_PATH = REFERENCE_DIR / "littlest-tokyo.official.html"

DEMO_CODE = 8
MATERIAL_CODE = 1
MATERIAL_COLOR = 0xFFFFFF
BACKGROUND_COLOR = 0x8FAFC2

CAMERA = {
    "fov": 40,
    "aspect": 760 / 520,
    "near": 1,
    "far": 100,
    "x": 5,
    "y": 2,
    "z": 8,
    "lookAtX": 0,
    "lookAtY": 0.7,
    "lookAtZ": 0,
}


def load_glb_json(path: Path) -> dict[str, Any]:
    with path.open("rb") as file:
        header = file.read(12)
        if len(header) != 12:
            raise RuntimeError(f"Invalid GLB header: {path}")
        magic, version, _length = struct.unpack("<III", header)
        if magic != 0x46546C67 or version != 2:
            raise RuntimeError(f"Unsupported GLB container: {path}")

        chunk_header = file.read(8)
        if len(chunk_header) != 8:
            raise RuntimeError(f"Missing GLB JSON chunk: {path}")
        chunk_length, chunk_type = struct.unpack("<II", chunk_header)
        if chunk_type != 0x4E4F534A:
            raise RuntimeError(f"First GLB chunk is not JSON: {path}")
        return json.loads(file.read(chunk_length).decode("utf-8").rstrip("\x00 "))


def number_literal(value: float) -> str:
    rounded = 0.0 if abs(value) < 0.000001 else value
    return f"{rounded:.6f}".rstrip("0").rstrip(".") or "0"


def collect_scene_stats(gltf: dict[str, Any]) -> dict[str, int]:
    accessors = gltf.get("accessors", [])
    meshes = gltf.get("meshes", [])
    nodes = gltf.get("nodes", [])
    scene = gltf["scenes"][gltf.get("scene", 0)]
    stats = {
        "parts": 0,
        "vertices": 0,
        "indices": 0,
        "skinnedParts": 0,
    }

    def visit_node(node_index: int) -> None:
        node = nodes[node_index]
        mesh_index = node.get("mesh")
        if mesh_index is not None:
            mesh = meshes[int(mesh_index)]
            for primitive in mesh.get("primitives", []):
                if primitive.get("mode", 4) != 4:
                    continue
                attributes = primitive.get("attributes", {})
                position_accessor_index = attributes.get("POSITION")
                if position_accessor_index is None:
                    continue
                vertex_count = int(accessors[int(position_accessor_index)]["count"])
                index_accessor_index = primitive.get("indices")
                index_count = (
                    int(accessors[int(index_accessor_index)]["count"])
                    if index_accessor_index is not None
                    else vertex_count
                )
                stats["parts"] += 1
                stats["vertices"] += vertex_count
                stats["indices"] += index_count
                if node.get("skin") is not None and ("JOINTS_0" in attributes or "WEIGHTS_0" in attributes):
                    stats["skinnedParts"] += 1

        for child_index in node.get("children", []):
            visit_node(int(child_index))

    for root_node_index in scene["nodes"]:
        visit_node(int(root_node_index))

    return stats


def write_generated_ts(stats: dict[str, int]) -> None:
    parts: list[str] = [
        "// Generated by scripts/generate-littlest-tokyo-reference.py from the official Three.js Littlest Tokyo GLB demo.",
        "",
        "import {",
        "  createGeaWebGLRendererLittlestTokyoScene,",
        "  type GeaWebGLRenderer,",
        "  logAngleHostSmoke,",
        "  renderGeaWebGLRendererMeshSceneFrame,",
        "  syncGeaWebGLRendererSize,",
        "} from './angleHost'",
        "",
        "export function startThreeFrameLoop(",
        "  renderer: GeaWebGLRenderer,",
        "  aspect: number,",
        "): void {",
        f"  const demoCode = {DEMO_CODE}",
        f"  const materialCode = {MATERIAL_CODE}",
        f"  const materialColor = {MATERIAL_COLOR}",
        f"  const backgroundColor = {BACKGROUND_COLOR}",
        f"  const cameraFov = {CAMERA['fov']}",
        f"  const fallbackCameraAspect = aspect > 0 ? aspect : {number_literal(CAMERA['aspect'])}",
        f"  const cameraNear = {CAMERA['near']}",
        f"  const cameraFar = {CAMERA['far']}",
        f"  const cameraX = {CAMERA['x']}",
        f"  const cameraY = {CAMERA['y']}",
        f"  const cameraZ = {CAMERA['z']}",
        f"  const cameraLookAtX = {CAMERA['lookAtX']}",
        f"  const cameraLookAtY = {CAMERA['lookAtY']}",
        f"  const cameraLookAtZ = {CAMERA['lookAtZ']}",
        "  const sceneHandle = createGeaWebGLRendererLittlestTokyoScene(",
        "    renderer,",
        "    demoCode,",
        f"    {json.dumps(str(ORIGINAL_GLB.resolve()))},",
        "  )",
        "  logAngleHostSmoke(",
        "    'official Three Littlest Tokyo GLB scene uploaded: parts='",
        f"      + {stats['parts']}",
        "      + ' vertices='",
        f"      + {stats['vertices']}",
        "      + ' indices='",
        f"      + {stats['indices']}",
        "      + ' skinnedParts='",
        f"      + {stats['skinnedParts']},",
        "  )",
        "",
        "  requestAnimationFrame(function frame(timestampMs: number): void {",
        "    const cameraAspect = syncGeaWebGLRendererSize(renderer, fallbackCameraAspect)",
        "    renderGeaWebGLRendererMeshSceneFrame(",
        "      renderer,",
        "      sceneHandle,",
        "      demoCode,",
        "      materialCode,",
        "      materialColor,",
        "      backgroundColor,",
        "      cameraFov,",
        "      cameraAspect,",
        "      cameraNear,",
        "      cameraFar,",
        "      cameraX,",
        "      cameraY,",
        "      cameraZ,",
        "      cameraLookAtX,",
        "      cameraLookAtY,",
        "      cameraLookAtZ,",
        "      0,",
        "      0,",
        "      0,",
        "      timestampMs,",
        "    )",
        "    requestAnimationFrame(frame)",
        "  })",
        "}",
        "",
    ]

    GENERATED_TS_PATH.write_text("\n".join(parts))
    GENERATED_SCENE_SOURCE_PATH.write_text("export {\n  startThreeFrameLoop,\n} from './generatedLittlestTokyoReference'\n")


def write_official_html() -> None:
    html = """<!DOCTYPE html>
<html lang="en">
	<head>
		<title>three.js webgl - animation - keyframes</title>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">
		<meta property="og:title" content="three.js webgl - animation - keyframes">
		<meta property="og:type" content="website">
		<meta property="og:url" content="https://threejs.org/examples/webgl_animation_keyframes.html">
		<meta property="og:image" content="https://threejs.org/examples/screenshots/webgl_animation_keyframes.jpg">
		<link type="text/css" rel="stylesheet" href="../main.css">
		<style>
			body {
				background-color: #e2e0e0;
				color: #000;
			}

			a {
				color: #2983ff;
			}
		</style>
	</head>

	<body>

		<div id="container"></div>

		<div id="info">
			<a href="https://threejs.org" target="_blank" rel="noopener">three.js</a> webgl - animation - keyframes<br/>
			Model: <a href="https://artstation.com/artwork/1AGwX" target="_blank" rel="noopener">Littlest Tokyo</a> by
			<a href="https://artstation.com/glenatron" target="_blank" rel="noopener">Glen Fox</a>, CC Attribution.
		</div>

		<script type="importmap">
			{
				"imports": {
					"three": "../../../../node_modules/three/build/three.module.js",
					"three/addons/": "../../../../node_modules/three/examples/jsm/"
				}
			}
		</script>

		<script type="module">

			import * as THREE from 'three';

			import Stats from 'three/addons/libs/stats.module.js';

			import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
			import { Sky } from 'three/addons/objects/Sky.js';

			import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
			import { DRACOLoader, DRACO_GLTF_CONFIG } from 'three/addons/loaders/DRACOLoader.js';

			let mixer;

			const timer = new THREE.Timer();
			timer.connect( document );
			const container = document.getElementById( 'container' );

			const stats = new Stats();
			container.appendChild( stats.dom );

			const renderer = new THREE.WebGLRenderer( { antialias: true } );
			renderer.setPixelRatio( window.devicePixelRatio );
			renderer.setSize( window.innerWidth, window.innerHeight );
			renderer.toneMapping = THREE.ACESFilmicToneMapping;
			container.appendChild( renderer.domElement );

			const scene = new THREE.Scene();

			// Sky

			const sky = new Sky();
			sky.scale.setScalar( 10000 );
			scene.add( sky );

			const uniforms = sky.material.uniforms;
			uniforms[ 'turbidity' ].value = 0;
			uniforms[ 'rayleigh' ].value = 3;
			uniforms[ 'mieDirectionalG' ].value = 0.7;
			uniforms[ 'cloudElevation' ].value = 1;
			uniforms[ 'sunPosition' ].value.set( - 0.8, 0.19, 0.56 ); // elevation: 11, azimuth: -55

			const pmremGenerator = new THREE.PMREMGenerator( renderer );
			const environment = pmremGenerator.fromScene( sky ).texture;
			scene.environment = environment;

			const camera = new THREE.PerspectiveCamera( 40, window.innerWidth / window.innerHeight, 1, 100 );
			camera.position.set( 5, 2, 8 );

			const controls = new OrbitControls( camera, renderer.domElement );
			controls.enableDamping = true;
			controls.target.set( 0, 0.7, 0 );
			controls.update();

			const dracoLoader = new DRACOLoader();
			dracoLoader.setDecoderPath( DRACO_GLTF_CONFIG );

			const loader = new GLTFLoader();
			loader.setDRACOLoader( dracoLoader );
			loader.load( 'models/gltf/LittlestTokyo.glb', function ( gltf ) {

				const model = gltf.scene;
				model.position.set( 1, 1, 0 );
				model.scale.set( 0.01, 0.01, 0.01 );
				scene.add( model );

				mixer = new THREE.AnimationMixer( model );
				mixer.clipAction( gltf.animations[ 0 ] ).play();

				renderer.setAnimationLoop( animate );

			}, undefined, function ( e ) {

				console.error( e );

			} );

			window.onresize = function () {

				camera.aspect = window.innerWidth / window.innerHeight;
				camera.updateProjectionMatrix();

				renderer.setSize( window.innerWidth, window.innerHeight );

			};

			function animate() {

				timer.update();

				const delta = timer.getDelta();

				mixer.update( delta );

				controls.update();

				stats.update();

				renderer.render( scene, camera );

			}


		</script>

	</body>

</html>
"""
    OFFICIAL_HTML_PATH.write_text(html)


def main() -> None:
    gltf = load_glb_json(ORIGINAL_GLB)
    stats = collect_scene_stats(gltf)
    if stats["parts"] == 0:
        raise RuntimeError("No Littlest Tokyo mesh primitives were found")

    write_generated_ts(stats)
    write_official_html()

    print("Generated Three Littlest Tokyo GLB reference")
    print(
        f"parts={stats['parts']} vertices={stats['vertices']} "
        f"indices={stats['indices']} skinnedParts={stats['skinnedParts']}"
    )
    print(GENERATED_TS_PATH)
    print(OFFICIAL_HTML_PATH)
    print(ORIGINAL_GLB)


if __name__ == "__main__":
    main()
