export const appTitle = 'Native device APIs'
export const appSubtitle = 'MapKit, CoreLocation, and AVFoundation mounted from TypeScript'

export const mapTitle = 'Live map surface'
export const mapDetail = 'MKMapView with user tracking'
export const cameraTitle = 'Camera preview'
export const cameraDetail = 'Full-screen AVCaptureSession with native controls'

export const locationIdle = 'Location idle'
export const locationRequested = 'Location requested. Simulator may need a location set.'
export const locationUpdated = 'Location fix applied to the map'

export const cameraReady = 'READY'
export const cameraNoCamera = 'NO CAMERA'
export const cameraUnavailable = 'No camera device on this simulator'
export const cameraInputUnavailable = 'Camera input unavailable'
export const cameraRunning = 'READY'
export const cameraZoomUpdated = 'ZOOM'
export const cameraFocusUpdated = 'AE/AF LOCKED'
export const cameraGridOff = 'GRID OFF'
export const cameraGridOn = 'GRID ON'
export const cameraToolsHidden = 'TOOLS HIDDEN'
export const cameraToolsVisible = 'TOOLS VISIBLE'
export const cameraFlashOff = 'FLASH OFF'
export const cameraFlashAuto = 'FLASH AUTO'
export const cameraFlashOn = 'FLASH ON'
export const cameraNoRecentCapture = 'NO RECENT CAPTURE'
export const cameraConfigurationUnavailable = 'Camera configuration lock unavailable'
export const cameraOutputUnavailable = 'Photo output unavailable'
export const cameraCapturing = 'CAPTURING'
export const cameraCaptured = 'SAVING'
export const cameraSaved = 'SAVED TO PHOTOS'
export const cameraCaptureFailed = 'CAPTURE FAILED'
export const cameraSaveFailed = 'PHOTOS SAVE FAILED'
