// Generated by scripts/generate-littlest-tokyo-reference.py from the official Three.js Littlest Tokyo GLB demo.

import {
  createGeaWebGLRendererLittlestTokyoScene,
  type GeaWebGLRenderer,
  logAngleHostSmoke,
  renderGeaWebGLRendererMeshSceneFrame,
  syncGeaWebGLRendererSize,
} from './angleHost'

export function startThreeFrameLoop(
  renderer: GeaWebGLRenderer,
  aspect: number,
): void {
  const demoCode = 8
  const materialCode = 1
  const materialColor = 16777215
  const backgroundColor = 9416642
  const cameraFov = 40
  const fallbackCameraAspect = aspect > 0 ? aspect : 1.461538
  const cameraNear = 1
  const cameraFar = 100
  const cameraX = 5
  const cameraY = 2
  const cameraZ = 8
  const cameraLookAtX = 0
  const cameraLookAtY = 0.7
  const cameraLookAtZ = 0
  const sceneHandle = createGeaWebGLRendererLittlestTokyoScene(
    renderer,
    demoCode,
    "<repo>/apps/three-angle-metal-prototype/reference/littlest-tokyo/models/gltf/LittlestTokyo.glb",
  )
  logAngleHostSmoke(
    'official Three Littlest Tokyo GLB scene uploaded: parts='
      + 71
      + ' vertices='
      + 193125
      + ' indices='
      + 425406
      + ' skinnedParts='
      + 8,
  )

  requestAnimationFrame(function frame(timestampMs: number): void {
    const cameraAspect = syncGeaWebGLRendererSize(renderer, fallbackCameraAspect)
    renderGeaWebGLRendererMeshSceneFrame(
      renderer,
      sceneHandle,
      demoCode,
      materialCode,
      materialColor,
      backgroundColor,
      cameraFov,
      cameraAspect,
      cameraNear,
      cameraFar,
      cameraX,
      cameraY,
      cameraZ,
      cameraLookAtX,
      cameraLookAtY,
      cameraLookAtZ,
      0,
      0,
      0,
      timestampMs,
    )
    requestAnimationFrame(frame)
  })
}
